# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-19 14:08
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactsApp', '0004_auto_20180218_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='externalID',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$', 'Некорректный телефонный номер')]),
        ),
    ]
